#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
ksuperkey &
flameshot &
picom &
~/.fehbg &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           10
bspc config border_radius	     8
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config normal_border_color  "#ABB2BF"
bspc config focused_border_color "#61AFEF"